title: Nate Mulatu # your name (or website title) here
logo: "/images/Untitled design.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Data-driven professional looking for new opportunities to bring value to your business. <br><br> 
  Tech Stack: SQL, Python, Power BI, Tableau, and Excel. <br><br>
  <a href="https://www.linkedin.com/in/natemulatu/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
